# How to run

# conda env create -f environment.yml
# To use env: conda activate wsd
name: wsd
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - scikit-learn=1.3.0
  - numpy
  - scipy
  - joblib
